name: Setup node and install packages

description: |-
  Setup nodes and install packages for build and tests

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install packages
      run: yarn install
      shell: bash
