name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build-services-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build api service
        uses: ./services/api

  build-middlewares:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build middlewares
        uses: ./packages/middlewares
